### ISSUE TITLE
Kyle Chaya

### ISSUE THREAD

**Issue by kchaya** [laboon/Capstone_Fall2017#76]
13 Oct
29 Sept
27 Oct

**Comment by laboon** [comment]
Kyle - This came in after the deadline (12 Noon on Wednesday) and so I am  manually adding it after the TA made the assignments.  All of these dates are currently full, so the best date I can give you is 8 DEC.

**Comment by laboon** [comment]
You got lucky!  Somebody asked to move so you are now scheduled for 13 OCT.
